### ISSUE TITLE
Screen Reader Support

### ISSUE THREAD

**Issue by StormProductionsMusic** [PeterStrick/ViVeTool-GUI#17]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when having to ask for sighted help to use this GUI. I'm a blind person, so screen readers are vital while using my PC. 

**Describe the solution you'd like**
I'd love to see this GUI having accessibility labels and controls. I personally use NVDA as my screen reader, but accessibility framework don't differ that much. 

You can find NVDA here: https://github.com/nvaccess/nvda

Thanks!

**Comment by PeterStrick** [comment]
I am currently testing V i V e Tool GUI 1.7 with NVDA 2022.1 and I got it working to say the Text of Labels, Buttons, Table Cells, and Headers. Although sometimes it speaks useless information instead of the text like Telerik.Wincontrols.UI.RadGridView 2135 5, which I can´t figure out why it is doing that, or even where the numbers come from.

**Comment by PeterStrick** [comment]
There seems to be an incompatibility between Screen Readers and Telerik UI for WinForms 2021.3.1109.

I am afraid that I currently cannot help you, or fix this issue because I do not have access to newer Versions of Telerik UI for WinForms.

Options for you would be to use the original V i V e Tool in a Command Prompt, or to manually enter a Feature ID, that you found online in V i V e Tool GUI by pressing the "Manually enter a Feature ID" Button, or by hitting F12 inside V I V e Tool GUI
