### ISSUE TITLE
[Bug] Error on launch: Microsoft Edge can't read/write

### ISSUE THREAD

**Issue by zwresn453** [PeterStrick/ViVeTool-GUI#78]
**Describe the bug**
When launching the program, [this error appears](https://imgur.com/a/DOSMsXS). The error reappears about 60 seconds later.

VTGUI is completely unable to load the flags (the things that can be turned on/off).

**To Reproduce**
1. Launch the program

~~If the error does not occur, try installing MSEdgeRedirect (system-wide mode, all checkboxes enabled), then restart VTGUI.~~
Edit: This problem also occurs on an installation that does not have MSEdgeRedirect installed. 

Is there a log that I can submit, or something that I can try?

**Screenshots**
[https://imgur.com/a/DOSMsXS](https://imgur.com/a/DOSMsXS)

**Desktop (please complete the following information):**
 - Windows Build: 11 22h2 22621
 - ViVeTool-GUI Version: 1.6.2

**Comment by PeterStrick** [comment]
One of the caveats of pushing out the Beta Release in #77 is that it was only tested with Portable Versions of ViVeTool, sorry about that

This issue should be fixed by giving the User Read Write Access to the ViVeTool GUI Folder, starting ViVeTool GUI as an Administrator, or using the Portable Version

**Comment by PeterStrick** [comment]
This should be fixed by changing the Installation directory within the Installer for the 1.7 Release
