### ISSUE TITLE
Explanation/renaming of Feature Scanner function

### ISSUE THREAD

**Issue by zwresn453** [PeterStrick/ViVeTool-GUI#79]
**Is your feature request related to a problem? Please describe.**
If the user, for whatever reason, wishes to update the list of flags (the features that the program turns on/off), they would first look for a Reload button. Because this is not present in VTGUI (as far as I can see), they might then run the Feature Scanner, which kind of sounds like what they are trying to do, but as I understand it, this feature is not meant to be used by the average user. 

(Non-technical users can see warning labels as annoying "things" that need to be ignored and clicked past in order to "make it work", which could be dangerous depending on how dangerous the Feature Scanner is.)

**Describe the solution you'd like**
Addition of a Reload button, which would reload the available flags.
Renaming of Feature Scanner, or a more dramatic "Warning: Not for the average user" warning when launching Feature Scanner.

**Comment by PeterStrick** [comment]
A reload Button is generally not really needed due to the list of Flags not changing once loaded in. The Status of each Flag (whether it is Enabled or Disabled) is checked while the Flag is added to the List within ViVeTool GUI

The Feature Scanner is generally not Dangerous, it just needs you to have the Windows SDK/ADK installed, some 50GB of Disk Space, and a lot of patience while it downloads Debug Symbols from Microsoft's Servers, analyzes them and makes a Feature List out of that

**Comment by PeterStrick** [comment]
Closing due to no response, the Description will be changed accordingly
